ai_classification_csv: C:\Users\willo\OneDrive - UNSW\Documents\Work\CES\Wild Deserts\Image
  classification\coding\app\config/config_2025-08-04.csv
folders: E:/WD Camera traps/2025_02_WCAM_originals\outputs
output_dir: C:\Users\willo\OneDrive - UNSW\Documents\Work\CES\Wild Deserts\Image classification\coding\app\final_outputs/
parent_dir: E:/WD Camera traps/
